
-- --------------------------------------------------------

--
-- Structure de la table `subjects`
--

DROP TABLE IF EXISTS `subjects`;
CREATE TABLE `subjects` (
  `subject_id` int NOT NULL,
  `subject` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

--
-- Déchargement des données de la table `subjects`
--

INSERT INTO `subjects` (`subject_id`, `subject`) VALUES
(1, 'Allemand'),
(2, 'Analyse et conduite de la relation commerciale'),
(3, 'Analyse financière'),
(4, 'Anglais'),
(5, 'Atelier Innov\'EPA'),
(6, 'Atelier de professionnalisation'),
(7, 'Atelier de recherche de stage'),
(8, 'Bilan social et audit'),
(9, 'Bureautique'),
(10, 'Commerce International'),
(11, 'Communication Interne et Externe'),
(12, 'Communication et management interculturel'),
(13, 'Culture Economique, Juridique et Managériale'),
(14, 'Culture Générale et Expression'),
(15, 'Droit'),
(16, 'Droit - Gestion'),
(17, 'Démarche Qualité'),
(18, 'Développement des Unités Commerciales'),
(19, 'Economie Droit'),
(20, 'Economie générale'),
(21, 'Epreuve semestrielle : Allemand, écrit'),
(22, 'Epreuve semestrielle : Analyse diagnostique des marchés étrangers'),
(23, 'Epreuve semestrielle : Anglais, écrit'),
(24, 'Epreuve semestrielle : Culture générale et Expression'),
(25, 'Epreuve semestrielle : Culture économique, juridique et managériale'),
(26, 'Epreuve semestrielle : Droit'),
(27, 'Epreuve semestrielle : Droit Gestion'),
(28, 'Epreuve semestrielle : Economie Générale'),
(29, 'Epreuve semestrielle : Economie droit'),
(30, 'Epreuve semestrielle : Espagnol, écrit'),
(31, 'Epreuve semestrielle : Gestion'),
(32, 'Epreuve semestrielle : Gestion commerciale'),
(33, 'Epreuve semestrielle : Gestion de la Relation Commerciale'),
(34, 'Epreuve semestrielle : Gestion de la relation client'),
(35, 'Epreuve semestrielle : Gestion des relations avec les clients et les fournisseurs'),
(36, 'Epreuve semestrielle : Management des entreprises'),
(37, 'Epreuve semestrielle : Management et gestion des Unités Commerciales'),
(38, 'Epreuve semestrielle : Montage des opérations d\'import export'),
(39, 'Epreuve semestrielle : Production d\'une prestation touristique'),
(40, 'Epreuve semestrielle : Production d\'une prestation touristique : Mercatique'),
(41, 'Epreuve semestrielle : Prospection et suivi de clientèle'),
(42, 'Epreuve semestrielle : Relation client et animation de réseaux'),
(43, 'Epreuve semestrielle : Relation client et négociation vente'),
(44, 'Epreuve semestrielle : Relation client à distance et digitalisation'),
(45, 'Epreuve semestrielle : Soutenir le fonctionnement et le développement de la Pme'),
(46, 'Epreuve semestrielle : Tourisme et Territoires'),
(47, 'Epreuve semestrielle : communication interne et externe'),
(48, 'Epreuve semestrielle : développement des unités commerciales'),
(49, 'Epreuve semestrielle: Communication et management interculturels'),
(50, 'Espagnol'),
(51, 'Etude et veille des marchés étrangers'),
(52, 'Etudes et Activités Commerciales'),
(53, 'Finalités du Marketing'),
(54, 'Gestion commerciale'),
(55, 'Gestion comptable et financière'),
(56, 'Gestion de la relation Commerciale'),
(57, 'Gestion de la relation client'),
(58, 'Gestion des Relations avec les Clients et les Fournisseurs'),
(59, 'Gestion des opérations d\'import-export'),
(60, 'Géopolitique'),
(61, 'Histoire Géographie'),
(62, 'Informatique commerciale'),
(63, 'Intégration en Entreprise'),
(64, 'Le recrutement en anglais'),
(65, 'Management de l\'équipe commerciale'),
(66, 'Management des Entreprises'),
(67, 'Management et Gestion des UC'),
(68, 'Mercatique'),
(69, 'Montage d\'une prestation touristique'),
(70, 'Négociation commerciale'),
(71, 'Outils bureautiques'),
(72, 'Outils de gestion'),
(73, 'Prospection et suivi de clientèle'),
(74, 'Pérennisation de l\'entreprise'),
(75, 'Qualité RH'),
(76, 'Relation client et animation de réseaux'),
(77, 'Relation client et négociation vente'),
(78, 'Relation client à distance et digitalisation'),
(79, 'Réseaux sociaux'),
(80, 'Révisions'),
(81, 'Segmentation stratégique'),
(82, 'Soutenir le fonctionnement et le développement de la Pme'),
(83, 'Séance inaugurale'),
(84, 'Séance introductive'),
(85, 'Team building'),
(86, 'Tourisme et Territoires'),
(87, 'Travaux Dirigés Tourisme et Territoires'),
(88, 'Utilisation stratégique des ratios financiers'),
(89, 'Vente appliquée aux produits touristiques'),
(90, 'Webmarketing');
